### ISSUE TITLE
Compilation error with ERTS 10.0 (OTP 21)

### ISSUE THREAD

**Issue by mischov** [mischov/meeseeks#43]
Attempts to compile with ERTS 10.0 yield the following error:

```
error: failed to run custom build command for `erlang_nif-sys v0.6.3`
```

[Rustler needs to be updated for OTP21](https://github.com/hansihe/rustler/issues/158), after which meeseeks_html5ever and meeseeks will be updated.

**Comment by mischov** [comment]
Fixed in `v0.10.0`.
