### ISSUE TITLE
Compilation error with ERTS 9.2

### ISSUE THREAD

**Issue by mischov** [mischov/meeseeks#30]
Attempts to compile with ERTS 9.2 yield following error

```
error: failed to run custom build command for `erlang_nif-sys v0.6.2`
```

For more information, see: https://github.com/mischov/meeseeks_html5ever/issues/9

**Comment by mischov** [comment]
Fixed in v0.7.7.
